---
- hosts: apache
  become: yes
  gather_facts: no
  pre_tasks:
    - name: pinging the servers
      ping: ~

    - name: Install basic softwares for running ansible
      raw: "apt update && apt install python-minimal -y"
    
  tasks:
    - name: Install Apache2 software
      apt:
        name: apache2
        state: latest
        update_cache: yes
    
    - name: Install other software depencies for php for custom website
      apt:
        name: php7.0
        state: installed
        update_cache: yes

    - name: Copy the index file to the server
      copy:
        src: website/
        dest: /var/www/html/
        owner: root
        group: root
        mode: '0755'

    - name: copy the basic installation script to the server
      copy:
        src: basicrequisites/basicPhp.sh
        dest: /tmp/basicPhp.sh
        mode: '0555'

    - name: run the script to enable php
      command: bash -lc "bash -x /tmp/basicPhp.sh"

    - name: change the permission to data file
      file:
        path: /var/www/html/data.txt
        mode: '0777'

    - name: Start the web server
      service: 
        name: apache2
        state: restarted
