---
- hosts: apache
  become: yes
  gather_facts: no
  pre_tasks:
    - name: Install basic softwares for running ansible
      raw: "apt update && apt install python-minimal -y"
    
  tasks:
     - name: Giving access to sudo without password
       lineinfile:
         path: /etc/sudoers
         line: "{{ lookup('env','USER') }} ALL=(ALL) NOPASSWD:ALL"
         state: present

     - name: Installing Basic Softwares
       apt: 
         name: "{{item}}"
         state: latest
         force: yes
         update_cache: yes
       with_items:
         - vim
         - git
         - python-minimal
         - awscli
         - apt-transport-https 
         - ca-certificates
         - openssh-server
         - curl 
         - gnupg-agent 
         - software-properties-common
         - jq
         - zip
         - unzip
         - net-tools
         - tmux
         - htop
         - openvpn
         - tree
         - meld
         - graphviz
         
    - name: Install Apache2 software
      apt:
        name: apache2
        state: latest
        update_cache: yes
    
    - name: Install other software depencies for php for custom website
      apt:
        name: php
        state: installed
        update_cache: yes

    - name: Copy the index file to the server
      copy:
        src: websiteCode/
        dest: /var/www/html/
        owner: root
        group: root
        mode: '0755'

    - name: copy the basic installation script to the server
      copy:
        src: basicrequisites/basicPhp.sh
        dest: /tmp/basicPhp.sh
        mode: '0555'

    - name: run the script to enable php
      command: bash -lc "bash -x /tmp/basicPhp.sh"
      ignore_errors: yes

    - name: change the permission to data file
      file:
        path: /var/www/html/data.txt
        mode: '0777'

    - name: Start the web server
      service: 
        name: apache2
        state: restarted
